Rework azure rate limit retry logic and add chunking
cloud-carbon-footprint/cloud-carbon-footprint pull request #1059
Opened 2023-02-17 22:29 UTC by NicolasBissig

## Description of Change

fixes #1058 

- [X] added max retries and logging with hint on how to fix
- [X] added support for "day based chunking" of Azure requests to handle large requests, that would otherwise result in an infinite loop
- [X] added config option to turn on chunking and set chunk size in days

## Checklist

- [X] PR description included and stakeholders cc'd
- [ ] tests are changed or added
- [ ] yarn test passes
- [X] yarn lint has been run
- [X] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [ ] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
- [ ] relevant documentation is changed or added

## Notes

Additional information relevant to the changes

© 2021 Thoughtworks, Inc.

2023-02-28 21:47 UTC, 4upz requested changes
Hi @NicolasBissig thanks again for implementing this! I've included a few notes from my review. 

The biggest thing that I noticed is that using any form of chunking for requests with multiple subscriptions causes a longer time to execute as well as more frequent rate limits and logging. Sometimes this will also lead to dropped/hanging requests. This is likely due to how we handle multiple requests in [AzureAccount.ts](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/azure/src/application/AzureAccount.ts#L82) where we make the request for each subscription in parallel.

I think it's fine to have longer requests when using chunks with multiple accounts, and other fixes and improvements for multiple subscriptions can be incorporated into and implemented with #1022. For the scope of this issue, I think it would be good to add a change in `AzureAccount.ts` where it switches to fetching each subscription sequentially whenever chunking is enabled -- just to ensure that it still plays nice for those with more than one subscription.

Feel free to let me know if you have any questions or thoughts 😄

2023-02-28 21:47 UTC, 4upz commented on packages/azure/src/lib/ConsumptionManagement.ts
> +    if (!AZURE.CONSUMPTION_CHUNKS_DAYS || AZURE.CONSUMPTION_CHUNKS_DAYS === 0) {
0 is considered a falsy value, so the second condition may not be needed as the first will also return true for a value of 0.
```suggestion
    if (!AZURE.CONSUMPTION_CHUNKS_DAYS) {
```

2023-02-28 21:47 UTC, 4upz commented on packages/azure/src/lib/ConsumptionManagement.ts
> +      `Time range is going to be requested in chunks of ${AZURE.CONSUMPTION_CHUNKS_DAYS} days`,
Just more concise wording
```suggestion
      `Time range will be requested in chunks of ${AZURE.CONSUMPTION_CHUNKS_DAYS} days`,
```

2023-02-28 21:47 UTC, 4upz commented on packages/cli/.env.template
> +AZURE_RESOURCE_TAG_NAMES=["resourceGroup"] # eg. ["resourceGroup","project","customer"]
Nice catch! Thanks for adding this here!

2023-02-28 22:19 UTC, NicolasBissig commented
@4upz thanks for the review, will take a look at it tomorrow!

2023-03-01 13:22 UTC, NicolasBissig commented
@4upz I have resolved all mentioned items.

The failing tests also fail on the trunk branch for me, so it seems the failures were not caused by these changes...

Hope all is good now, otherwise let me know!

2023-03-02 00:09 UTC, 4upz approved these changes
Awesome, the changes look great! Thanks again for working on this @NicolasBissig 

The failing tests were in fact unrelated and were caused by a bug that has been fixed on trunk. So no worries about those. I'll go ahead and merge this in! 😄🚀

2023-03-02 00:09 UTC, merged