feat: add script for mock data
cloud-carbon-footprint/cloud-carbon-footprint pull request #1087
Opened 2023-03-23 07:16 UTC by Samridhi-98

## Description of Change

Fixes:  #532 

## Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] tests are changed or added
- [x] yarn test passes
- [ ] yarn lint has been run
- [ ] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [ ] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
- [ ] relevant documentation is changed or added

© 2021 Thoughtworks, Inc.

2023-03-28 15:22 UTC, camcash17 commented
Hi @Samridhi-98, just checking in! Did you mean to make this a draft PR? Did you want us to start reviewing?

2023-03-28 15:55 UTC, Samridhi-98 commented
> Hi @Samridhi-98, just checking in! Did you mean to make this a draft PR? Did you want us to start reviewing?

Hi Cam, work is still in progress for this PR.

2023-03-28 18:35 UTC, camcash17 requested changes

2023-03-28 18:35 UTC, camcash17 commented on scripts/index.js
> +//CO2e -> kilowattHours * emissions[region];
Once this is merge-ready, you can remove unnecessary comments and console logs

2023-03-28 18:35 UTC, camcash17 commented on scripts/index.js
> +function updateCO2eData() {
i would suggest making this async and just naming the function `main` to align with our other scripts

2023-03-28 18:35 UTC, camcash17 commented on scripts/index.js
> +updateCO2eData();
with the above comment about renaming to "main", the calling of the function can be updated to the following:
```
main().catch((error) => {
  console.error(error.stack)
  process.exit(1)
})
```

2023-03-28 18:35 UTC, camcash17 commented on scripts/index.js
> +        serviceEstimates.forEach((data) => {
rather than 'data', consider 'serviceEstimate' to avoid confusion with the other data variable in scope defined earlier

2023-03-28 18:35 UTC, camcash17 commented on scripts/index.js
> +            let co2e = data.kilowattHours * emissions.mtPerKwHour;
these variables can both be constants

2023-03-28 18:41 UTC, camcash17 commented
> > Hi @Samridhi-98, just checking in! Did you mean to make this a draft PR? Did you want us to start reviewing?
> 
> Hi Cam, work is still in progress for this PR.

Thanks for working on this! I made a few comments/suggestions in my review and it looks good so far.

A few points I am thinking of:

- Don't worry about cost. That can remain a manually added figure.
- Would you want to consider adding the same update functionality for the Recommendations co2e savings calculation? It would be the same logic multiplying the kwh savings by the emissions factor associated with that region
- Something important that we want to chance is updating the timestamp of the footprint service estimates to remain recent. Would you want to consider enhancing the script to update the time stamps to be the last 15 months from the current date?
- This might be out of scope, but we should consider making the emissions factors in the mockData.json consistent with actual values in our coefficients. For example, [here](https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients/blob/main/data/grid-emissions-factors-aws.csv) is the list for AWS regions.

2023-03-28 18:46 UTC, camcash17 commented on scripts/index.js
> +function updateCO2eData() {
with this change, I would also request changing the name of the file from index.js to something like 'updateMockData.js'

2023-03-29 04:24 UTC, Samridhi-98 commented
> 

Thanks for reviewing Cam.
I will make all the changes you suggested.

2023-03-29 04:24 UTC, Samridhi-98 commented
> > > Hi @Samridhi-98, just checking in! Did you mean to make this a draft PR? Did you want us to start reviewing?
> > 
> > 
> > Hi Cam, work is still in progress for this PR.
> 
> Thanks for working on this! I made a few comments/suggestions in my review and it looks good so far.
> 
> A few points I am thinking of:
> 
> * Don't worry about cost. That can remain a manually added figure.
> * Would you want to consider adding the same update functionality for the Recommendations co2e savings calculation? It would be the same logic multiplying the kwh savings by the emissions factor associated with that region.
> * Something important that we want to change is updating the timestamp of the footprint service estimates to remain recent. Would you want to consider enhancing the script to update the time stamps to be the last 15 months from the current date?
> * This might be out of scope, but we should consider making the emissions factors in the mockData.json consistent with actual values in our coefficients. For example, [here](https://github.com/cloud-carbon-footprint/cloud-carbon-coefficients/blob/main/data/grid-emissions-factors-aws.csv) is the list for AWS regions. The reason for this is that the mockData is used on our public facing [demo](https://demo.cloudcarbonfootprint.org/) and cloud service providers are expecting it to reflect actual values.

Thanks for reviewing Cam.
I will make all the changes you suggested.

2023-04-04 15:12 UTC, camcash17 approved these changes

2023-04-04 15:12 UTC, merged