fix: recommendation amount formatting error, recommendation last 30 days error
cloud-carbon-footprint/cloud-carbon-footprint pull request #1155
Opened 2023-05-26 09:37 UTC by kevinmonvoisin-reply

## Description of Change

Issue: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/1138

In the recommendations tab, there was a couple of errors.
1. Last 30 day total was showing a wrong value. Before it was the sum of every values since the date in the configuration environment file or environment variable. Now it displays the value from last 30 days as expected
2. In the recommendations table, the potential cost saving value was wrong. For instance, if the value was 1,234, it would show 1234. Now, it shows 1,23. We only need 2 digits after comma

## Checklist

- [x] PR description included and stakeholders cc'd
- [x] tests are changed or added
- [x] yarn test passes
- [x] yarn lint has been run
- [x] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [x] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
## Notes

Both @bgauchon-reply and I are working on this PR.

© 2021 Thoughtworks, Inc.

2023-06-01 20:07 UTC, 4upz requested changes
Thanks for opening this PR and submitting this fix @kevinmonvoisin-reply! 

There are a few changes I'd recommend making before this is merge-ready:

- There are some lint formatting errors in the `transformData.ts` file. I believe these may be highlighted by the Github Actions check. If they're not visible,  I'd recommend running `yarn lint:fix` in the client to fix them.

- For filtering the last 30 days to be calculated, the current function works but it may be doing more work than necessary for larger date ranges. We accomplish a similar task in `RecommendationsPage.tsx` with a function that we use to check if a recent 30-day range exists. I'd recommend looking into reusing the `sliceFootprintDataByLastMonth` function that is imported from the `src/utils/helpers/handleDates.ts` file to directly get the last month of data or to reduce the amount of timestamps to be iterated over.

2023-06-13 13:11 UTC, kevinmonvoisin-reply commented
Hi @4upz, sorry for the delay.

I've made the changes in my PR and included the function you pointed out to me.
This time, I also made sure that lint is correct :)

2023-06-13 14:25 UTC, 4upz commented
No worries and thank you, @kevinmonvoisin-reply! 

The changes look good to me! The only thing left is that there seems to be some tests for `transformData.test.ts` and `RecommendationsServiceHook.test.ts` that are failing and need to be updated to reflect the changes. If you run `yarn test` in the `packages/client` directory, it should show which ones.

Is this something you'd be willing to look into? Happy to take care of it if not.

2023-06-14 14:23 UTC, kevinmonvoisin-reply commented
Hi @4upz,
If that's ok for you, can you handle it? Otherwise, I can take a look.

2023-06-19 21:57 UTC, 4upz commented
@kevinmonvoisin-reply No worries! I went ahead and took care of it. Thanks again for your help on this! I'll merge in the changes

2023-06-19 21:58 UTC, merged