Update CostAndUsageReports.ts with try/catch error handling to enable unknown data to be gracefully handled
cloud-carbon-footprint/cloud-carbon-footprint pull request #1226
Opened 2023-08-24 20:54 UTC by bendemora

Within the getEstimatesFromInputData() function (line 156 onwards):

1: Wrapped the processing of each row (both from inputData and unknownRows) inside a try-catch block.
2: In case of an error, log the problematic row along with the error message to the console.

## Description of Change

Write a brief but concise description of the changes you have made while also making sure to **link the relevant issue number to this PR** _( e.g. fixes #ISSUE-NUMBER - optional short description)_

## Checklist

- [X] PR description included and stakeholders cc'd
- [ ] tests are changed or added
- [X] yarn test passes
- [ ] yarn lint has been run
- [ ] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [ ] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
- [ ] relevant documentation is changed or added

## Notes

Additional information relevant to the changes

© 2021 Thoughtworks, Inc.

2023-08-31 19:02 UTC, camcash17 requested changes
I think this is a great start @bendemora! i have a few questions on the location of the error handling itself and if the issue you are facing would actually lead to the catch blocks.

Also as an FYI - currently this PR is aiming to merge into `cloud-carbon-footprint:changeset-release/trunk`. This should just be `cloud-carbon-footprint:trunk`.

Thank you for taking the time to create this PR!

2023-08-31 19:02 UTC, camcash17 commented on packages/aws/src/lib/CostAndUsageReports.ts
> +    const result: LookupTableOutput[] = [];
I think you can undo these changes where you add the semi-colons. It may not play well with the linter

2023-08-31 19:02 UTC, camcash17 commented on packages/aws/src/lib/CostAndUsageReports.ts
> +      } catch (error) {
did you confirm that this will in fact reach the catch block? i am not sure that the issue here would actually trigger an error, however, I may be wrong.

2023-08-31 19:02 UTC, camcash17 commented on packages/aws/src/lib/CostAndUsageReports.ts
> +        } catch (error) {
Same thought as above. I think if the error we are trying to fix is the NaN issue, we may be better to error handle at the root where the arithmetic occurs to aggregate the results. I could also see this potentially being console warnings.

2023-10-12 18:53 UTC, camcash17 commented
Hi @bendemora have you had any chance to look at the requested changes / questions?

2023-10-31 15:56 UTC, bendemora commented
Hey Cameron,

Really sorry I've not had the ability to put work aside and spend time
trying to code (it's been a really long time since I last wrote any
software, so I had a go at this but it's unsurprising that my approach was
wrong)

Your thoughts on how to improve (or really, introduce) error handling here
would be welcome.

Cheers,

Ben

On Thu, 12 Oct 2023 at 19:53, Cam Casher ***@***.***> wrote:

> Hi @bendemora <https://github.com/bendemora> have you had any chance to
> look at the requested changes / questions?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/1226#issuecomment-1760202722>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH3BXV6KNVQXJJARC5WITK3X7A4DBAVCNFSM6AAAAAA35SSX7SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRQGIYDENZSGI>
> .
> You are receiving this because you were mentioned.Message ID:
> <cloud-carbon-footprint/cloud-carbon-footprint/pull/1226/c1760202722@
> github.com>
>

2026-05-14 22:02 UTC, closed without merging