Add recs pagination in header and footer
cloud-carbon-footprint/cloud-carbon-footprint pull request #542
Opened 2021-10-23 16:24 UTC by jgrumboe

## Description of Change

This adds pagination in the header and is a retry of #462.
I like it as my first Typescript contribution. 

It will solve #453.

## Checklist

- [x] PR description included and stakeholders cc'd
- [ ] tests are changed or added
- [x] yarn test passes
- [x] yarn lint has been run
- [x] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [ ] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
- [ ] relevant documentation is changed or added

2021-10-23 16:29 UTC, jgrumboe commented
I'm somehow stuck here and there are two things left, where I need help.
1. I think I managed to separate the `CustomPagination` into its own file but now get a TS warning:
  ```
/Users/jgrumboeck/git/jgrumboe/cloud-carbon-footprint/packages/client/src/pages/RecommendationsPage/RecommendationsTable/CustomPaginaton.tsx
  16:10  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

✖ 1 problem (0 errors, 1 warning)
  ```
  Don't know how to get rid of it.

2. I didn't manage to refactor the function parameters into props. Tried but didn't find a good example for me I could understand and therefore don't know what to change. Sorry.

2021-10-23 21:05 UTC, jgrumboe commented
@ericksod
@4upz-tw

2021-10-25 22:43 UTC, 4upz-tw requested changes

2021-10-25 22:43 UTC, 4upz-tw commented on packages/client/src/pages/RecommendationsPage/RecommendationsTable/CustomPaginaton.tsx
> +  return () => {
This duplicated return can be removed. You only need one which is on line 20.

2021-10-25 22:43 UTC, 4upz-tw commented on packages/client/src/pages/RecommendationsPage/RecommendationsTable/CustomPaginaton.tsx
> +) {
You can add a return type for this component called `ReactElement` which is imported from `React`. 

```suggestion
function CustomPagination(
  handlePageSizeChange: (event: React.ChangeEvent<{ value: unknown }>) => void,
): ReactElement {
```

2021-10-25 22:43 UTC, 4upz-tw commented on packages/client/src/pages/RecommendationsPage/RecommendationsTable/RecommendationsTable.tsx
> +                Pagination: CustomPagination(handlePageSizeChange),
To fix the double return and the type issue in the Pagination file, the assigned components can be changed to return ReactElements as followed:

```suggestion
                Toolbar: () => CustomPagination(handlePageSizeChange),
                Pagination: () => CustomPagination(handlePageSizeChange),
```

2021-10-25 22:47 UTC, 4upz-tw commented
@jgrumboe Thanks for continuing to work on this! It looks and works good! Here are some responses to your concerns:

1. If you submit an additional commit with the suggested changes from my review, it should fix that TS warning you were referencing. After you commit those changes, I can merge everything in and close this out 😎

2. No worries at all! We can always refactor it after. If you'd like, I can commit the change after the merge and link you to the commit so you can see an example and hopefully make more sense of what I meant.

2021-10-26 12:58 UTC, jgrumboe commented on packages/client/src/pages/RecommendationsPage/RecommendationsTable/CustomPaginaton.tsx
> +  return () => {
ok

2021-10-26 13:01 UTC, jgrumboe commented on packages/client/src/pages/RecommendationsPage/RecommendationsTable/RecommendationsTable.tsx
> +                Pagination: CustomPagination(handlePageSizeChange),
ok

2021-10-27 07:41 UTC, jgrumboe commented
@4upz-tw 
Hi Arik,
Thanks for your comments. I changed and pushed it recently.
And yes, please commit the refactor changes and link me to the commit.
Cheers, Johannes

2021-10-28 10:15 UTC, jgrumboe commented
btw: regarding Hacktoberfest it would be nice to get a "hacktoberfest-accepted" label 😊

2021-10-28 21:27 UTC, 4upz-tw approved these changes
Looks good! Thanks again, @jgrumboe! I'll go ahead and merge this in, and of course, add the hacktoberfest-accepted label to it 🎉

2021-10-28 21:29 UTC, merged